<?php

namespace AppBundle\Repository;

/**
 * CustomerNoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerNoteRepository extends \Doctrine\ORM\EntityRepository
{
}
