<?php

namespace AppBundle\Repository;

/**
 * SalesPersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalesPersonRepository extends \Doctrine\ORM\EntityRepository
{
}
