<?php

namespace AppBundle\Repository;

/**
 * ShowOrderItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShowOrderItemRepository extends \Doctrine\ORM\EntityRepository
{
}
