<?php

namespace AppBundle\Repository;

/**
 * ShowOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShowOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
